# コードの自動補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_start_up = 1
let g:deoplete#max_list = 1000
let g:deoplete#auto_complete_delay = 0
set previewheight=5
inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1


# slimのシンタックスハイライト
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

# ES6のシンタックスハイライト
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

# Rubyの自動補完
[[plugins]]
repo = 'Shougo/deoplete-rct'
on_ft = ['ruby']

# Rubyの自動補完
[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = ['ruby']

# Rubyの自動補完
[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
hook_add = '''
let g:monster#completion#rcodetools#backend = "async_rct_complete"
let g:deoplete#sources#omni#input_patterns = {
  \ "ruby" : '[^. *\t]\.\w*\|\h\w*::',
  \}
'''

# Rubyのend補完
[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']


# Rubyのメソッドの定義元にジャンプ
[[plugins]]
repo = 'szw/vim-tags'


[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
hook_add = '''
  let g:neosnippet#snippets_directory='~/dotfiles/snippets/'
'''
on_i = 1

[[plugins]]
repo = 'takkii/ruby-dictionary3'
