# plugin管理
[[plugins]]
repo = 'Shougo/dein.vim'

# 非同期処理全般
[[plugins]]
repo = 'Shougo/vimproc.vim'

# autosave
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = '''
let g:auto_save_in_insert_mode = 0
'''

# vim-submode
[[plugins]]
repo = 'kana/vim-submode'

# colorschema
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

# color solarized
[[plugins]]
repo = 'ujihisa/unite-colorscheme'

# color twilight
[[plugins]]
repo = 'vim-scripts/twilight'

# color molokai
[[plugins]]
repo = 'tomasr/molokai'

# color material
[[plugins]]
repo = 'jdkanani/vim-material-theme'

# color nefertiti
[[plugins]]
repo = 'jeetsukumaran/vim-nefertiti'


# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# 無駄な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# j, k高速化
[[plugins]]
repo = 'rhysd/accelerated-jk'

# /検索強化
[[plugins]]
repo = 'osyo-manga/vim-anzu'

# f検索強化
[[plugins]]
repo = 'rhysd/clever-f.vim'

# ファイルオープンを便利に
[[plugins]]
repo = 'Shougo/unite.vim'

# サイドバー表示
[[plugins]]
repo = 'scrooloose/nerdtree'

# インデントを見やすくしてくれる
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# vim上からgit command
[[plugins]]
repo = 'tpope/vim-fugitive'

# html css 爆速
[[plugins]]
repo = 'mattn/emmet-vim'


